### ISSUE TITLE
Attacks not working 

### ISSUE THREAD

**Issue by pwned4ever2** [Leeon123/Aoyama#18]
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
TypeError: SentCmd() takes 3 positional arguments but 5 were given

When i run every attack in the list it doesn't start and gives me this error. Can you give me a hand please?

**Comment by ghost** [comment]
What are you typing in when you try and send the attack? 
_"TypeError: SentCmd() takes 3 positional arguments but 5 were given"_
