### ISSUE TITLE
huh?

### ISSUE THREAD

**Issue by pwned4ever2** [Leeon123/Aoyama#21]
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
TypeError: SentCmd() takes 3 positional arguments but 5 were given

**Comment by pwned4ever2** [comment]
When I launch an attack it shows this and crashes the cnc server
